"""empty message

Revision ID: a4f094fab1aa
Revises: 
Create Date: 2017-11-15 17:01:18.437436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f094fab1aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data1', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model1_data1'), 'model1', ['data1'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model1_data1'), table_name='model1')
    op.drop_table('model1')
    # ### end Alembic commands ###
